### ISSUE TITLE
.erdconfig not being detected

### ISSUE THREAD

**Issue by walkerab** [voormedia/rails-erd#150] opened 2015-06-18 20:41 UTC
Hi

I'm creating this `.erdconfig` in the root of my Rails app

```
attributes:
  - content
  - foreign_key
  - inheritance
  - timestamps
disconnected: true
filename: billing
filetype: pdf
indirect: false
inheritance: true
markup: true
notation: simple
orientation: vertical
polymorphism: true
sort: false
warn: true
title: false
exclude: null
only:
  - Client
  - TrialCode
  - TrialInfo
  - ClientStat
  - User
prepend_primary: true
```

However it doesn't seem that any of the options are being detected.

I am able to set all of the options through the command line except for `sort`. Which may or may not be related.

```
rake erd sort=false orientation=vertical attributes=foreign_keys,content,inheritance,primary_keys,timestamps only="Client,TrialCode,TrialInfo,ClientStat,User" title=false filename=billing
```

**Comment by bf4** [comment] 2015-06-18 21:17
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Please read CONTRIBUTING.md file for more information about creating bug reports. Thanks!

**Comment by bf4** [comment] 2015-06-18 21:18
Sorry about that, copypasta on accident.  Anyhow, please include your Rails-erd version, Rails version, Ruby type, any version manager, etc. A sample app would be fantastic so we can reproduce

**Comment by walkerab** [comment] 2015-06-18 21:26
rails-erd (1.4.0, 1.1.0)
Rails 3.1.10
ruby 1.9.3p448 (2013-06-27 revision 41675) [x86_64-darwin14.3.0] installed using rvm

I don't what you mean by Ruby type.

It's closed source so I don't think I can provide much in the way of a sample app.

**Comment by walkerab** [comment] 2015-06-19 16:06
Another piece of information that may be relevant:

The docs say the default value for `sort` is false. If I generate a diagram without specifying any options, the columns *are* being sorted.

**Comment by ygelfand** [comment] 2015-06-24 13:16
Have sort of the same issue, but more details, looks like the problem is choice's default values.  RailsERD::Diagram#initialize does 

`@domain, @options = domain, RailsERD.options.merge(options)`

Where options is default values coming from choice. This wipes any matching keys loaded from .erdconfig.  I think the best solution would be to not use the 'default' values for choice, that will still allow command line options to override .erdconfig options (and defaults are populated elsewhere anyway, via default_config).

**Comment by kerrizor** [comment] 2015-08-22 16:29
Would love to see a PR to fix this :)

**Comment by kerrizor** [comment] 2015-09-27 13:18
I believe this is fixed in #166

**Closed by kerrizor** 2015-09-27 13:18 UTC
Labels: Bug

**Comment by thom-nic** [comment] 2016-04-18 15:15
I am seeing this issue in v1.4.2, rails 4.2, ruby 2.2.

If I do `bin/erd` it correctly picks up config values in .erdconfig.  However if I do `bin/rake erd` it does not.

**Comment by damienlethiec** [comment] 2017-04-14 14:34
Same here, I have this issue with ruby 2.3.1, rails 5.0.1 and rails-erd 1.5

**Comment by rmros** [comment] 2018-01-07 15:35
hey everybody i solve
in your rails app folder type:
nano .erdconfig
and then paste 
`
attributes:
  - content
  - foreign_key
  - inheritance
  - primary_keys
  - timestamps
disconnected: true
filename: erd
filetype: pdf
indirect: true
inheritance: true
markup: true
notation: simple
orientation: horizontal
polymorphism: tre
sort: true
warn: true
title: ERD_diagram
exclude: null
only: null
only_recursion_depth: null
prepend_primary: true
cluster: false
splines: spline

`
and then rake erd
easy

**Comment by kerrizor** [comment] 2018-01-09 04:21
This is an issue due to a split in how we handle `$ erd` versus `$ rake erd` - the first invokes the binary, the 2nd a rake task. #289
