### ISSUE TITLE
Using --only with a single model from command line

### ISSUE THREAD

**Issue by vzamanillo** [voormedia/rails-erd#231] opened 2016-11-28 12:56 UTC
I was looking for an example of using `--only` from the command line, I suppose only expects an String to conform an array

`--only="ModelA,ModelB"`

But I don't know how to pass a single model, actually I am doing something like this:

`--only="ModelA, "`

with

`--only="ModelA"`

fails because is an String not an array.

**Comment by kerrizor** [comment] 2016-12-04 20:30
Oh! That's an awesome bug! We should fix that maybe..

**Comment by kerrizor** [comment] 2017-04-19 19:08
I was unable to reproduce this error in the 1.5.0 release. Closing for now, but if you'd like to reopen, can you also supply your version of RailsERD?

**Closed by kerrizor** 2017-04-19 19:08 UTC
Labels: Bug

**Comment by vzamanillo** [comment] 2017-04-19 19:25
Hey!! I am using 'rails-erd', '1.5', I will test again and I will let you know, it could be an error produced by me.
